### ISSUE TITLE
limit pulls

### ISSUE THREAD

**Issue by aesher9o1** [aesher9o1/git-buddy#12]
`git-buddy -a`

pulls all the repo in the list.
Add something like 
`git-guddy-am 10` which will set maximum repos to fetch to first 10 of repo.json

**Comment by galczo5** [comment]
Can I try?

**Comment by aesher9o1** [comment]
Sure :)

**Comment by galczo5** [comment]
https://github.com/aesher9o1/git-buddy/pull/15
